version: '3.8'
services:
  backend:
    build: .
    command: ./start
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
    stdin_open: true
    tty: true
  
  db:
    image: postgres:14
    expose:
      - "5432"
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - ./db/pg-data:/var/lib/postgresql/data
